### ISSUE TITLE
Comando WRITE reinicia o sistema

### ISSUE THREAD

**Issue by arthur-cas** [FrancisBFTC/KiddieOS_Development#14]
Estava vendo o comando WRITE mas ele reiniciou o KiddieOS quando usei ele errado. Depois fui ver as opções dele. Daí quando eu coloco o arquivo com 1 letra na extensão ele reinicia também. Inclusive em outros casos também

**Comment by FrancisBFTC** [comment]
Ah sim, então tem estes casos mesmo que ele não aceita, terei que colocar uma condicional pra impedir isso ou ao menos mostrar ao usuário que tem um erro ali na formatação. Por exemplo: No KiddieOS ainda não aceita arquivos com 1 letra na extensão, você precisa obrigatoriamente inserir 3 letras pra seguir no padrão 8.3, a menos que eu faça certas mudanças no FAT16 pra ele aceitar arquivos com uma letra na extensão. Eu testando aqui, eu vi que o Write Reinicia se eu colocar write ola mundo, sem aspas, aí eu tenho que mostrar um erro pro usuário, dizendo que é preciso colocar aspas, porque se não ele vai interpretar o "ola" e o "mundo" como dois argumentos, que aliás não existiria, então ele falaria: "O argumento 'ola' e 'mundo' não existe".

**Comment by FrancisBFTC** [comment]
Vou fazer aqui por enquanto as anotações de bugs que encontrei, que causam a reinicialização e a medida que eu for encontrando, vou editando este comentário:

### Bugs encontrados
- Reinicia quando coloca uma frase/palavra sem aspas após o comando "write".
- Quando mais de uma String são separadas por escape "\n", a última String substitui a String anterior, ou seja, se colocar "Frase1\nFrase2\nFrase3\n", ele apresentará apenas Frase3 na tela.

### Possíveis soluções

**Comment by FrancisBFTC** [comment]
Mudanças de plano: Aquilo que eu falei sobre controlar as aspas quando a String está após os parâmetros -fc ou -fa, eu mudei de ideia! Eu percebi algo, que sem querer o write obteve uma nova função quando não colocamos as aspas na String (neste segundo caso), esta função se trata do comando imprimir na tela os últimos dados escritos no arquivo, mesmo assim, ele escreve o último dado normalmente quando não tem aspas. Porém isso só vai funcionar pro parâmetro -fa, que é pra acrescentar dados nos arquivos. No entanto é obrigatório inserir aspas na String a partir do momento que a String está antes dos parâmetros -fc ou -fa, se caso não inserir (neste primeiro caso) aí o comando exibe um erro na tela de parâmetro inválido. Pelo fato dos dados anteriores do arquivo serem imprimidos na tela quando a String está sem aspas no segundo caso, tive a ideia de criar um novo parâmetro chamado "-hi", que significa "hidden" ou "oculto", ou seja, é quando o usuário não quer colocar aspas e mesmo assim não quer também que apareça os dados anteriores na impressão e este novo parâmetro ele teve algo legal também no comando, que se caso você quiser escrever um novo dado no arquivo e você tem a plena certeza que este novo dado estará no final do arquivo e você não quer manipular nada que estava anteriormente, você pode optar por usar o -hi pra dizer ao comando que você não quer imprimir os dados anteriores do arquivo, apenas acrescentar os novos dados. Vou dá um exemplo de cinco situações:

### 1ª situação:

`write -fa hello.txt "Ola mundo3"` - Neste caso, como tem aspas, não vai apresentar os dados anteriores, só acrescentar a nova String.

### 2ª situação:

`write -fa hello.txt \nOla mundo4` - Neste caso, como não tem aspas, o comando vai imprimir na tela os últimos dados armazenados, como o "Ola mundo3" armazenado anteriormente, e vai acrescentar mais "Ola mundo4".

### 3ª situação:

`write -hi -fa hello.txt \nOla mundo5` - Este é igual o caso anterior, com a diferença de que tem o parâmetro -hi (obrigatoriamente sempre no início), então ele não vai imprimir na tela os últimos dados armazenados (como no caso anterior), mas ainda vai armazenar o "Ola mundo5" igual o caso anterior.

 ### 4ª situação:

`write -hi -fa hello.txt` - Sabendo que você tem as 3 Strings no arquivo: "Ola mundo3", "Ola mundo4" e "Ola mundo5", separados por quebras de linhas, você agora não quer ver estes dados novamente, então você adiciona um -hi pra ocultar eles, e aí vai abrir o editor pra você em branco (limpo, sem nada), e você pode adicionar novos dados digitando pelo teclado, como por exemplo: Ola mundo6. Isso significa que você sabe que o dado vai ficar no final do arquivo e sua intenção é apenas esta, então não será preciso ver os dados anteriores se você não quiser, então só oculte com -hi.

`write -fa hello.txt` - Neste caso é quando você precisa alterar os dados anteriores, ou seja, provavelmente você vai pressionar um backspace e apagá-los pra poder substituir-los por outros novos dados, então não necessariamente você queira adicionar dados no final do arquivo, mas apagar por exemplo, então você não pode usar o parâmetro -hi, pois você quer "ver" os seus dados anteriores.

Observações: o novo parâmetro -hi só será útil para o comando -fa, pois o parâmetro -fa (File Append) é pra acrescentar novos dados, e isso considera que o arquivo já existe, por isso há a necessidade de ocultar ou ver os dados anteriores. Já no caso do -fc (File Create), o arquivo é dado como novo, sem dados anteriores. E na 2ª e 3ª situação como eu expliquei lá no início do texto, os dados só são apresentados em tela, no caso da String ser na linha de comando, se você realmente estiver usando -fa e a String estiver no final do comando (após os parâmetros -fa), e sem aspas também, estas são as condições, mas não vai dar certo se caso você fizer algo assim: `write \nOla mundo -fa hello.txt`, ou assim, `write "Ola mundo" -hi -fa hello.txt`, ou até mesmo assim `write -hi -fc hello.txt`, ... destas formas, não vai surtir o efeito do -hi, e neste 1ª exemplinho ali, dará até erro de parâmetro inválido pelo fato da String está sem aspas antes do parâmetro -fa. Então por ser um comando um pouco mais complexo, são regras que deve ficar atento.

No mas, todos os outros erros já foram corrigidos, a reinicialização, as quebras de linhas indevidas, a falta de identificação do cursor na hora voltar na linha anterior, tudo isso já foi corrigido. Amanhã vou revisar melhor outras coisas e qualquer já subo aqui, pra poder ter commits mais rápidos na semana. Boa noite.

**Comment by FrancisBFTC** [comment]
É, finalmente conseguir corrigir o Write completamente. Se tiver algum erro, deve ser algum bem específico que eu não consigo encontrar, porque já testei todas as possibilidades. Vou ver se consigo encontrar uma forma prática de processar as setas direcionais.

**Comment by arthur-cas** [comment]
Acabei de ler os seus comentários. Já pode marcar como concluído.

**Comment by FrancisBFTC** [comment]
Beleza!! Agora que tu captou tudo, eu vou atualizar amanhã a tarde. Porque fui adicionando novas atualizações no Editor do Write, e não tá 100% estável. Quero chegar a pelo menos uns 95% de estabilidade. Muitas coisas já ta dando certo, tô bem feliz agora por essas mudanças, mais um tempinho eu consigo e subo amanhã.

**Comment by FrancisBFTC** [comment]
Eae man! Subir já pro Github as atualizações, vou realizar o merge agora da Pull request. Se quiser ver lá o que foi implementado com detalhes, as novas funções, as descrições disso estão aqui https://github.com/FrancisBFTC/KiddieOS_Development/pull/16. 

No youtube também mostro a utilização do que foi atualizado:
https://www.youtube.com/watch?v=OWPTbTGlfk4

Fecharei esta issue com este comentário, valeu!
