### ISSUE TITLE
Dúvidas sobre o KiddieOS (nome/marca)

### ISSUE THREAD

**Issue by ghost** [FrancisBFTC/KiddieOS_Development#19]

**Comment by FrancisBFTC** [comment]
Olá @lucasnuic , levei um tempo responder pois passei o dia ocupado hoje. Mas irei responder todas. Alterei o nome da Issue pra ser identificar melhor. Uma dica quando for criar Issues: Coloque títulos que representem o tema da Issue, pra quando alguém entrar e ler, saber exatamente do que se trata.

Algumas destas perguntas são dúvidas que respondi na central de boas-vindas na comunidade do Discord e em alguns posts do Facebook, mas nunca escrevi por aqui, então vou explicar de uma forma mais abrangente e completa pra ficar registrado aqui...

**Comment by FrancisBFTC** [comment]
1. Por que utilizar uma nomenclatura internacional como o inglês "KiddieOS"?

Isto é devido a ser uma língua falada por praticamente quase todos os países. O inglês é a língua mais falada no mundo inteiro e tudo que fazemos na tecnologia, normalmente estará em Inglês, como: Termos técnicos, Sintaxes de linguagens de programação, etc. Existe até um jargão, se você fala inglês você fala com todos! E pior que é a pura verdade, a maioria dos países desenvolvidos ou não, usa como seu segundo idioma o Inglês. E este idioma está em tudo quando falamos de tecnologia. Então, acredito que colocar nomes ingleses em produtos, mesmo que seja natural do Brasil por exemplo, estende os horizontes deste produto para vários países, sem se prender a nacionalidade fixa. A missão do KiddieOS é ser internacional (Todos os países) e não nacional (Só o Brasil).

2. Por que o nome não pode ser algo brasileiro?

O fato do nome não "poder" brasileiro é pelo motivo citado acima, mas isso até que vai de cada um também. Tem pessoas que preferem colocar nomes em seus projetos seguindo sua língua nativa e não tem nada de errado nisso, mas vamos colocar um exemplo de um Russo que criou um jogo e nomeou seu jogo de "Боевые Боги" (Deuses da batalha). Um brasileiro não vai entender, provavelmente um americano também não e aquele jogo vai ficar restrito apenas a aquele país devido a sua "Marca". Mas se colocar em Inglês, tem maiores chances do brasileiro, do americano e vários países entender o nome do jogo.

3. Por que utilizar o nome KiddieOS? Da onde veio esse nome?

O nome KiddieOS não foi apenas um nome aleatório, mas ele vem de "Kid" de "Crianças". Por que Crianças? É como se este sistema fosse um bebê, uma criança nascendo, engatinhando, descobrindo formas do mundo real, imitando seus pais e aqueles a sua volta, aprendendo com o meio no qual se interage. É um sistema em evolução, em construção. Um dos intuitos iniciais do KiddieOS é ter um ambiente realmente similar a um ambiente de uma criança: Fácil de aprender, fácil de usar, divertido e de entretenimento. É como se este sistema fosse um completo "parque de diversões", onde aprenderíamos de uma forma divertida e didática conceitos de sistemas operacionais e programação. Essa ideia de envolver crianças em assuntos de tecnologia é algo que vem desde alguns pais da computação que tiveram esse mesmo pensamento, de ensinar crianças a programar. Como: Seymour Papert, que desenvolveu a linguagem LOGO e Alan Kay, que também participou desses projetos do Papert. Mas nem sempre um nome de um projeto pode vir de algo "Lógico" ou uma "Ideologia", pois ela pode vir de algo que o próprio autor gosta, por exemplo: Se um programador X adora morangos e decide colocar StrawBerry (Morango) como nome do projeto, isso pode pegar e muitos fazem isto. Quer um exemplo? O Próprio JAVA, antes tinha outro nome, que era Oak. Por que? Simples, quando eles estavam desenvolvendo, viu uma árvore lá fora que um idioma específico era Oak, e colocaram esse nome. Depois mudaram pra JAVA, por que novamente? Porque JAVA era o nome do café que eles bebiam muito durante a construção da linguagem. Então isso é normal acontecer, colocar um nome de acordo com as experiências do próprio projetista ou por algo aleatório que ele tenha visto. No meu caso, também já tive experiência com crianças, eu ensinava programação para crianças e jovens e sempre gostei de crianças.

**Comment by FrancisBFTC** [comment]
4. E por que não colocar nome do projeto relacionado a cultura brasileira como Brasis OS, Macuxi Os, Terena OS, Guarani OS?

Isto já foi explicado no texto anterior e estes nomes não teria nada a ver com o intuito do projeto e nem mesmo seria a essência do projeto. Mas sim, isso não impede de outra pessoa criar um projeto baseado no KiddieOS focado para índios e/ou apenas para o povo brasileiro como BrasilOS e GuaraniOS, NordesteOS, e eu teria a honra de compartilhar isso nas minhas timelines se acontecer, mas o intuito inicial do meu projeto não é esse. Hoje em dia tem gente criando nome pra tudo e temáticas para todos os fins, vai da criatividade e necessidade de cada um. (Peço pra pesquisa na sessão de projetos a variedade de nomes de projetos que se encontra no wiki.osdev.org/projects).

5. Outra pergunta, eu tenho que falar inglês para participar desse projeto? 

De forma alguma. Não precisa se comunicar em Inglês pra participar desse projeto, até porque ele ainda não atingiu uma extensão tão grande assim em outros países, apesar de que já tem 1 colaborador Holandês, que aliás nos comunicamos apenas em Inglês (Pois eu não sei Holandês e nem ele Brasileiro, viu a importância do Inglês?). Estamos conversando em português agora, certo? Isso já é um bom sinal que não será necessário do Inglês pra participar. Mas te dou uma dica: Estude Inglês. É importante até para a área geral da tecnologia, porque programadores só escrevem códigos e códigos foram feitos por americanos, então é bom sim ter uma noçãozinha do Inglês pra saber o que significa... Igual os termos que você me disse nos seus outros comentários "End Users", "Home Users"... São termos da nossa área e quando temos uma noçãozinha, a gente compreende a linguagem do outro.

**Comment by FrancisBFTC** [comment]
5. O nome do sistema operacional não deveria ser fácil? 

E KiddieOS é um nome fácil. Eu escolhi esse nome exatamente por ser fácil, pois já vi vários outros por aí (Que é open-source) que é quase impronunciável. Kiddie lido como "Kidi" mesmo, já traz a sensação de algo "Infantil", "Brincalhão", "Divertido", "Focado pra crianças"... mesmo que não só Crianças utilizem, porém a "Ideologia" por trás deste sistema, o conceito em si. Isso você vai ver muito, se você der uma boa procurada aí, principalmente no link que eu te enviei de projetos na wiki de sistemas operacionais de entusiastas como eu, verá que é uma prática comum colocar "OS" (Operating System) no final de algum nome, nome este que pode parecer muito aleatório, mas cada um tem seus motivos como foi explicado.

7. O público-alvo é quem pode contribuir falando e escrevendo português?

Sim, exatamente. E não há problemas de aparecer um contribuinte Russo, Holandês, querendo se comunicar em Russo e em Holandês, eu vou atendê-los da mesma forma. O Google Tradutor ta aí pra isso né? Rs... Com o tradutor a gente conversa com qualquer país igualmente. Meu inglês também nem é perfeito, muito menos fluente, mas já acostumei fazer muitas coisas em linguagem inglesa, já faz parte da minha vida. Mas todos que vier falando em português, pra mim será melhor ainda, porque aí me comunico de uma forma mais aberta, clara, detalhada e tranquila, sem precisar ficar me preocupando com as normas do Inglês. Mas códigos de programação, Labels, Nomes de funções, naturalmente eu sempre faço em Inglês, até mesmo por convenções. É super comum na nossa área de T.I, os programadores já saber o básico de Inglês. Mas novamente, não é um critério aqui.

**Comment by FrancisBFTC** [comment]
> Se sim, não faria sentido usar um nome fácil para ser falado ou lembrado? Como B-OS? AC-OS(Asssembly, C)?
> 
> Se achar interessante, essa seria uma pequena contribuição de uma possível nome, design ou brad design.

Sim, faria sim, mas KiddieOS não é tão difícil, pelo menos não pra mim e para todos com quem eu me envolvi até agora. Não tenho a intenção de alterar esse nome porque ele já é a minha marca registrada. Daqui pra frente pretendo fazer até blusas com o Logotipo. Ele também tem um mascote próprio que é uma Lagartixa verde sorridente. Assim como o Linux tem um Pinguim, O Kid tem uma Lagartixa. (E cá comigo, não acho que "Linux" seja mais fácil de pronunciar do que "KiddieOS" kk Quem dirá "Unix" que é bem difícil). Mas se lembra que falei que o KiddieOS não seria comercial? E que ele seria só a base para um sistema maior que aí sim seria comercial? Então, o nome do outro sistema não vai ser KiddieOS, vai ser outro diferente, e o KiddieOS vai representar pelo menos 30% do outro sistema, e claro, depois do KiddieOS "todo" pronto. Então essa questão de nomes para o KiddieOS em si não seria tão relevante pra se pensar agora. Até porque ele será livre, gratuito, código-aberto, livre pra comunidade, sem fins lucrativos, sem muitas exigências comerciais. Se fosse comercial, primeiramente, eu já não teria colocado esse nome, porque esse tipo de nome se assemelha mais a projetos como TempleOS, MikeOS, etc... ou seja, Os Open-Source Underground mesmo. Mas o outro sistema que vai "derivar" do KiddieOS no Futuro, ela terá um nome mais amigável, mais comercial, seguindo as estratégias de marketing.

Mas isso sobre contribuição, não se preocupe com o "Nome do KiddieOS" agora, ou Logotipos, ou coisas do tipo. E agradeço por você tentar ajudar. Só te peço que você leia com calma os tipos de colaborações que eu enviei na outra Issue e reflita bem sobre elas. Algumas sugestões de mudanças ao meu ver pode não ser tão adequada assim ao sistema operacional no estado em que ele está agora, não só esta questão de Nomes, mas outras coisas também. É porque isso afeta um todo né, então não seria uma "pequena" contribuição e sim "Grande", porque afeta o todo (Marca registrada do Sistema). As melhores contribuições pra mim são aquelas citadas nos tipos de colaborações e a que você mencionou antes, as que vão acrescentar real valor ao projeto. Mas Toda ideia é bem-vinda e vou responder todas, inclusive as dúvidas como estas.
