### ISSUE TITLE
divulgação KiddieOS_Development

### ISSUE THREAD

**Issue by lucasnuic** [FrancisBFTC/KiddieOS_Development#20]
Oi @FrancisBFTC 

> *"Divulgação: Como você mencionou, essa será um dos primeiros tipos, não tendo uma ordem específica de execução, mas que tem igual relevância. A divulgação será pra atrair mais colaboradores, interessados e usuários. Também vai servir pra aumentar nossa comunidade, que já é existente no Discord e no Youtube (KiddieOS.Community, posso te passar o link mais tarde se não tiver lá). Você como divulgador, poderá até mesmo aumentar seu "Networking" e círculo de amizades de novos colaboradores, criar uma teia, uma rede de pessoas que te sigam e que até mesmo te "ajudem" a colaborar. É como se você fosse um professor alternativo do KiddieOS, que ajuda disseminar o conceito do KiddieOS nas redes sociais e grupos de programação."*

Eu não sei onde posso enviar uma tarefa concluída, no entanto pensei em criar uma issue chamada report para reportar ou relatar alguma colaboração feita, ou para avaliar se foi uma colaboração feita. de forma geral, divulguei o KiddieOS aqui: https://github.com/backend-br/opensource-br/pull/92

É um grupo interessante sobre backend e acho que backend é muito relacionado ao sistema operacional, banco de dados e linguagem de programação ou até mesmo algoritmos, estrutura de dados, técnicas de desenvolvimento de algoritmo e afins de forma teórica/prática se podemos dizer assim.

Se essa issue for marcada como concluída, vou entender que ajudei significativamente duas comunidades as quais participo e gosto bastante.

Talvez fosse interessante criar uma label para cada desenvolvedor ou interessado reportando aquilo que fez, como fez e onde fez para maior auditoria pública, transparente e significamente. A vantagem disso é que haveria um histórico público de várias divulgações que foram feitas, como foram feitas e onde foram feitas pela issue do GitHub

**Comment by FrancisBFTC** [comment]
Muito bom @lucasnuic! Muito obrigado pela divulgação! Isto realmente significa pra mim e você está contribuindo para comunidade. Vou marcar essa Issue como concluída.

Eu li lá no grupo que você fez, eu ia falar que não tinha nenhuma menção ao autor do sistema ou link de referência para canal no Youtube ou Repositório, mas depois eu vi que a menção é automática, então tranquilo. Como você divulgou dentro do Github, então por você realizar a menção aqui para o outro repo, automaticamente fica salvo lá como "lucas mentioned this pull request yesterday" e aí fica o Link pro repositório do Github, apesar de não ficar tão visível, mas tudo bem. Você já fez um bom trabalho!

No entanto, existe uma forma legal de divulgar também que é em redes sociais, por exemplo: Na maioria das vezes eu divulgo o canal do youtube do KiddieOS.Community junto com o Repositório na minha Timeline do Facebook, no LinkedIn, no feed do Instagram, em Stories (Em alguns casos) e na minha página do Facebook. Também divulgo em grupos de programação, que no facebook existem diversos grupos em T.I, participo de vários. Mas já tem um bom tempo que não estou divulgando em grupos específicos, apenas nos meus perfis mesmo. E aí, a cada atualização ou vídeo que eu subo do KiddieOS, eu crio uma descrição dizendo o que eu faço no vídeo e algumas mudanças posteriores. Seria interessante, se você for divulgar em alguma rede social, você me marcar e mencionar como autor do sistema, além de apresentar o Link pro canal e pro Github, e aí eu conseguiria ver sua postagem e dava um curtir lá (Seria uma forma também de acompanhar suas publicações sobre o KiddieOS).

Gostei da sua ideia final também, reportar alguma colaboração de divulgação para manter um registro. Poderíamos criar uma hashtag específica para inserir no título das divulgações, além da label que você mencionou, porém eu não sei se é possível criar uma label aqui no GitHub pra cada desenvolvedor, acho que só tem como adicionar apenas as padrões que o GitHub oferece para Issues, como: Bug, Question, Duplicate, Documentation, etc. Que são os tipos de Issues disponíveis referentes ao que acontece com o software em si... por exemplo: Se uma pessoa reporta algum Bug do Sistema que ela identificou, a Label é "Bug", se ela tiver alguma dúvida e realizar alguma pergunta, a label é "Question", Se ela quiser comentar sobre uma nova funcionalidade a ser adicionada, a label é "enhancement" e assim por diante. As labels também podem ser combinadas, se a missão da Issue é retratar mais de uma destas coisas. Mas para divulgações, não existe uma Label específica, porque acho que não é algo próprio para Issues (Já que Issues significa "Problemas"). Mas a gente pode adaptar sim para Issues, pelo menos criar uma #hashtag.

Exemplo: Digamos que eu criei uma nova funcionalidade pro KiddieOS e postei o vídeo no meu canal, e atualizei aqui uma nova branch do repositório para esta funcionalidade. A funcionalidade seria um mapeamento de memória. E aí, geralmente eu posto algumas descrições do que foi feito na funcionalidade e porquê, e o que ela significa. Aí digamos que você leu, viu o vídeo, baixou o repositório, testou, etc. etc. Desta forma, você compreendeu ali a funcionalidade e decide compartilhar isto no instagram, seja em um Story ou no seu Feed. No caso, você me mencionaria, dizendo que o "KiddieOS contém novas funcionalidades, referente ao gerenciamento de memória que pode ser útil para administrar o sistema de uma maneira melhor, etc..", você cria ali sua descrição, o seu texto da sua forma e especifica o Link para as pessoas acessar, tanto da nova branch que foi criada, quanto do novo vídeo postado no canal. Nesta, vai ter pessoas que vão curtir a sua postagem e clicar nos links pra conhecer mais do sistema. E aí na sua publicação, você geralmente pede pro pessoal compartilhar a sua postagem ou se tornar colaborar do sistema. O que acontece, neste caso, mesmo que você me marcasse lá no Instagram e eu curtisse o seu post, você pegaria o link de publicação do Instagram e jogaria aqui numa nova Issue, e colocaria a hashtag específica criada para publicações seguida de um título, exemplo: #post: **Divulgação de nova funcionalidade do KiddieOS | Mapeamento de memória**.

Outro exemplo: Você está divulgando uma resolução de bugs do KiddieOS no facebook, onde o bug resolvido foi do comando de navegação de diretórios. Neste caso o seu título da Issue seria algo como: #post: Divulgação de bug resolvido do KiddieOS | Comando CD. E aí, para cada Issue que você criou de alguma publicação, você faria um relatório do que foi publicado, especificando o que você comentou na publicação, talvez até copiando o texto da sua publicação e colando na Issue como Descrição. E aí já mescla essa ideia que você disse sobre o desenvolvedor reportar na Issue "Aquilo que fez, como fez e onde fez", que poderia ser por exemplo: Aquilo que fez - Divulgação de resolução do bug X; Como fez - Publicação com 2 imagens, link de repositório corrigido, link do vídeo de demonstração no canal e texto descritivo; Onde fez - Feed do LinkedIn, Story/Feed do Facebook, etc. E na Issue você colocaria o Link da divulgação e o "Como fez".

**Comment by FrancisBFTC** [comment]
@lucasnuic Agora que eu vi lá. É um repositório para projetos brasileiros né, muito bom! Vi que eles colocaram o KiddieOS na tabela lá, com a linguagem de desenvolvimento, etc. Obrigado por esta divulgação valiosa!!!
