### ISSUE TITLE
adicionar licença neste projeto?

### ISSUE THREAD

**Issue by stokebreakup** [FrancisBFTC/KiddieOS_Development#22]

**Comment by FrancisBFTC** [comment]
Olá, valeu por fazer a pergunta, então... É útil sim, eu ainda não adicionei por lerdeza, mas seria bom ter uma licença GPL ou GNU para tipos de distribuições. Ainda não tive um tempo pra avaliar isso melhor, preciso estudar os detalhes de cada tipo de licença pra saber exatamente qual vou adicionar. Em breve estarei voltando aqui e comentando sobre isso... Vou deixar essa Issue em aberto por enquanto.

**Comment by FrancisBFTC** [comment]
Licença adicionada! Por enquanto será esta.

https://github.com/FrancisBFTC/KiddieOS_Development/tree/KiddieOS_v1.3.12_4
