### ISSUE TITLE
adicionar releases?

### ISSUE THREAD

**Issue by stokebreakup** [FrancisBFTC/KiddieOS_Development#25]
Alguns devs não gostam de adicionar coisas extras na mesma área de desenvolvimento, pq quando vc baixa tudo, tudo fica grande e pesado. daí alguns fazem build separada na área do release.

"como?"
sempre que gerar a iso, é só dar um import na release deste repo que vc tem acesso ou somente vc tem acesso. ficaria mais fácil de encontrar os builds mais recentes ou antigos.

"nao entendi nada"
apenas dá uma lida no passo a passo aki `https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository` (explica como gerenciar o release de um projeto aberto, adicionar tags e adicionar manualmente o arquivo)

 bom seria fazer  o mesmo aki? (tm essa maneira aki também pela linha de comando github-cli `https://stackoverflow.com/questions/64936180/how-to-release-on-github-through-the-command-line-and-to-attach-a-large-file`)

**Comment by FrancisBFTC** [comment]
Esse é o post legal. Vou dar uma olhada pra ver o que posso fazer. Mas so lembrando que normalmente um projeto só é levado pro Release quando ele está quase terminando ou um uma fase estável de utilização é lançada, ou seja, um projeto finalizado. (Mesmo que seja um Beta). Esta ainda não é uma realidade do KiddieOS porque não está finalizado e está meio longe disso acontecer. De toda forma, vou dar uma olhada pra dar as primeiras estudadas sobre esse assunto.

**Comment by FrancisBFTC** [comment]
Não marque esta Issue como "Not planned". Vamos deixar ela aberta, em breve estarei trabalhando em disponibilizar estas releases quando as próximas versões estiverem estáveis para uso. Ainda estou trabalhando em novos sistemas planejados para as próximas versões.

**Comment by FrancisBFTC** [comment]
Olá @stokebreakup ! Uma release test foi gerada, achei legal! Vou passar a postar Releases... só não descrevi muito bem as últimas atualizações, mas cada atualização pretendo utilizar uma release com descrições. Está neste Link:

https://github.com/FrancisBFTC/KiddieOS_Development/releases/tag/KiddieOS-release

Também pode ser acessado pelo Main do KiddieOS_Development, na parte de Releases.
