### ISSUE TITLE
adicionar SEO?

### ISSUE THREAD

**Issue by stokebreakup** [FrancisBFTC/KiddieOS_Development#26]

**Comment by FrancisBFTC** [comment]
Olá, boa tarde! Seria útil sim! Por estes dias estou tentando me recuperar de uma gripe, quando me recuperar, vou adicionar as tags e buscar outras técnicas de SEO também.

**Comment by FrancisBFTC** [comment]
Adicionei algumas tags de SEO no repositório, mas depois adiciono mais e busco outras técnicas.
